### Site Settings ###
title               : Twisha Sahay
description         : >-
                      Deep Learning and Machine Learning Enthusiast | Student at SRM University
baseurl             : "/twisha-sahay"                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : ""     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : true                             # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Twisha Sahay
  image             : static/profile.jpeg
  github            : twisha-a
  email             : twishasahay@gmail.com
  linkedin          : twishaa-sahay-19952518b


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
